import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../static/provider-profile.js',import.meta.url),'utf8');
const {supportsProvider,profileLabel,renderProviderProfile}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const providers=[{id:'astra',name:'Astra',kind:'codex',capabilities:['*']},{id:'deepseek',name:'DeepSeek',kind:'deepseek',capabilities:['*']},{id:'manual',name:'Manual',kind:'manual',capabilities:['*']}];
const profile={mode:'deepseek',image_provider:'manual',deepseek:{model:'deepseek-flash',vision_model:'deepseek-flash',key_env:'DEEPSEEK_API_KEY',credential_configured:false}};
assert(!supportsProvider(providers[1],'image'));
assert(supportsProvider(providers[1],'new_skill'));
assert.equal(profileLabel({profile}),'Powered by DeepSeek');
assert.equal(profileLabel({profile:{mode:'custom'}}),'自訂服務商組合');
const html=renderProviderProfile({providers,profile},esc);
assert.match(html,/Powered by Astra/);assert.match(html,/Powered by DeepSeek/);
assert.match(html,/value="deepseek" selected/);
assert.match(html,/value="deepseek-flash"/);
assert.match(html,/不會回退至 Astra/);assert.match(html,/尚未設定/);
const renderer=html.match(/<select name="image_provider">([\s\S]*?)<\/select>/)[1];
assert(!renderer.includes('astra')&&!renderer.includes('deepseek'));assert(renderer.includes('manual'));
const hostile=renderProviderProfile({providers,profile:{...profile,deepseek:{...profile.deepseek,key_env:'"><script>bad</script>'}}},esc);
assert(!hostile.includes('<script>'));
const app=await readFile(new URL('../static/app.js',import.meta.url),'utf8');
assert.match(app,/api\('\/settings\/profile',values\)/);
assert.match(app,/api\('\/settings\/deepseek\/check',\{\}\)/);
assert.match(app,/settings\?\.profile\?\.default_provider/);
console.log('Provider profile UI checks passed: choices, coverage, credential state, rendering boundary and escaping.');
const {renderProductionMethod}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const protectedSettings=renderProviderProfile({providers,profile,production_methods:{mandatory:true,version:'1.0.0'}},esc);
assert.match(protectedSettings,/已強制套用/);
assert.equal(renderProductionMethod({},esc),'');
const method=renderProductionMethod({production_method:{mandatory:true,version:'1.0.0'},image_preparation_origin:{mode:'reused',job_id:'saved'},image_prompt_stage:'render',image_prompt:'<script>prompt text</script>'},esc);
assert.match(method,/沒有重新交給模型改寫/);
assert.match(method,/最終圖片提示詞/);
assert(!method.includes('<script>'));
console.log('Mandatory production method and reused-prompt UI checks passed.');
