import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source = await readFile(new URL('../static/director-page.js', import.meta.url), 'utf8');
const {createHandoffState, renderHandoff, transferReferences} = await import('data:text/javascript;base64,' + Buffer.from(source).toString('base64'));
const values = new Map();
const storage = {getItem: key => values.get(key), setItem: (key, value) => values.set(key, value)};
const chapter = (id, number) => ({shot_id:id,number,title:'鏡頭 '+number,duration:8,shot_prompt:'summary: \nDialogue: “Hello & goodbye” </textarea>',guidance:{enabled:number>1,previous_shot_id:number>1?'one':null,previous_title:'鏡頭 1',notes:'接續',cross_scene:false},issues:[]});
const scene = (id, chapters) => ({scene_id:id,title:'Scene '+id,global_prompt:'subject_definitions: <Picture 1>\n全域 & identity',references:[{asset_id:'asset-1',label:'Picture 1',name:'Ada <test>'}],missing_references:[],chapters});
const scenes = [scene('a',[chapter('one',1),chapter('two',2)]),scene('b',[chapter('three',3)])];
const p = {id:'project',delivery:{scenes,configuration:{continuity_enabled:true,context_frames:22}}};
const state = createHandoffState(storage);
assert.equal(state.selection(p.id, scenes).step,'shared');
state.select(p.id,'a','two');
state.markCopied(p.id,'a','two',scenes[0].chapters[1].shot_prompt);
assert.equal(createHandoffState(storage).selection(p.id, scenes).step,'two');
assert.equal(state.selection('another-project', scenes).step,'shared');
assert.ok(state.copied(p.id,'a','two',scenes[0].chapters[1].shot_prompt));
assert.ok(!state.copied(p.id,'b','two',scenes[0].chapters[1].shot_prompt));
assert.ok(!state.copied(p.id,'a','two','edited text'));
let html = renderHandoff(p,state);
assert.match(html,/素材組 2 → 提示詞/);
assert.match(html,/✓ 已複製 · 再複製/);
assert.match(html,/“Hello &amp; goodbye” &lt;\/textarea&gt;/);
assert.doesNotMatch(html,/subject_definitions:/); // Shot never copies/displays a second global.
assert.equal((html.match(/<textarea /g)||[]).length,1);
state.select(p.id,'b');
html=renderHandoff(p,state);
assert.match(html,/subject_definitions: &lt;Picture 1&gt;/);
assert.doesNotMatch(html,/Dialogue:/);
assert.match(html,/Ada &lt;test&gt;/);
assert.match(html,/全域提示詞只屬於 Scene/);
state.select(p.id,'a','deleted-shot');
assert.equal(state.selection(p.id, scenes).step,'shared');
state.select(p.id,'deleted-scene','three');
assert.equal(state.selection(p.id, scenes).scene.scene_id,'a');
assert.equal(state.selection(p.id, scenes).step,'shared');
const unavailable = createHandoffState({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}});
unavailable.select('p','a','two');
assert.equal(unavailable.selection('p',scenes).step,'two');
// Partial upload failures do not hide successful transfers or re-send those images on retry.
const refs=[{asset_id:'a'},{asset_id:'b'},{asset_id:'c'}],results={},calls=[],progress=[];
await transferReferences(refs,results,async id=>{calls.push(id);if(id==='b')throw Error('離線');return {name:id+'.png'};},()=>progress.push(JSON.stringify(results)));
assert.deepEqual(calls,['a','b','c']);
assert.equal(results.a.status,'sent');assert.equal(results.b.status,'failed');assert.equal(results.c.status,'sent');
assert.equal(results.b.error,'離線');assert.equal(progress.length,6);
await transferReferences(refs,results,async id=>{calls.push(id);return {name:id+'.png'};});
assert.deepEqual(calls,['a','b','c','b']);
assert.ok(Object.values(results).every(r=>r.status==='sent'));
assert.deepEqual(results.b.result,{name:'b.png'});
console.log('Director handoff: navigation, exact copy receipts, scene isolation, escaping, storage fallback and partial-transfer retry passed.');

// Recommendations are shown only after review; uncertain never becomes an off recommendation.
state.select(p.id,'a','two');
p.delivery.guidance_review={status:'ready',provider:'astra'};
for(const c of scenes.flatMap(s=>s.chapters))Object.assign(c.guidance,{continuityFromPrev:false,decision:'cut',reason:'由中景切至特寫，需重新建立構圖。',evidence:['Hard cut'],review_provider:'astra'});
html=renderHandoff(p,state);
assert.match(html,/由中景切至特寫，需重新建立構圖。/);
assert.match(html,/引用上段<\/span><strong>不勾選/);
assert.match(html,/查看分鏡判斷依據/);
Object.assign(scenes[0].chapters[1].guidance,{continuityFromPrev:null,decision:'uncertain',reason:'鏡頭延長與切鏡要求有衝突。'});
html=renderHandoff(p,state);
assert.match(html,/引用上段<\/span><strong>暫未能判斷/);
assert.match(html,/鏡頭延長與切鏡要求有衝突。/);
assert.doesNotMatch(html,/目前沒有鏡頭需要引用上段/);
console.log('Guidance rendering: reviewed off reason/evidence and unresolved decision passed.');
