import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const load=async f=>import('data:text/javascript;base64,'+Buffer.from(await readFile(new URL(f,import.meta.url),'utf8')).toString('base64'));
const {createPromptDrafts,promptSaveConfiguration}=await load('../static/prompt-editor.js');
const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
const drafts=createPromptDrafts(storage),p={id:'p',revision:3,delivery:{configuration:{revision:4,scenes:{s:{chapters:{a:{guidance_mode:'manual',guide_from_previous:false}}}},context_frames:22,continuity_enabled:true},scenes:[{scene_id:'s',global_prompt:'Global',chapters:[{shot_id:'a',shot_prompt:'Shot A'},{shot_id:'b',shot_prompt:'Shot B'}]}]}};
const d={base:'Shot A',text:'Shot A edited <d>…</d>',productionRevision:3};
drafts.set('p','s','a',d);
assert.deepEqual(createPromptDrafts(storage).get('p','s','a'),d);
assert.equal(drafts.get('other','s','a'),null);
assert.equal(drafts.get('p','s','b'),null);
const cfg=promptSaveConfiguration(p,'s','a',d);
assert.equal(cfg.scenes.s.chapters.a.shot_prompt,d.text);
assert.equal(cfg.scenes.s.chapters.a.prompt_edited,true);
assert.equal(cfg.scenes.s.chapters.a.guide_from_previous,false);
assert.equal(cfg.scenes.s.chapters.b.shot_prompt,'Shot B');
assert.equal(cfg.scenes.s.global_prompt,'Global');
assert.equal(p.delivery.configuration.scenes.s.chapters.a.shot_prompt,undefined);
assert.throws(()=>promptSaveConfiguration({...p,revision:4},'s','a',d),/草稿/);
assert.throws(()=>promptSaveConfiguration(p,'s','a',{...d,base:'changed elsewhere'}),/草稿/);
assert.throws(()=>promptSaveConfiguration(p,'s','a',{...d,text:'  '}),/不可留空/);
const global=promptSaveConfiguration(p,'s','shared',{base:'Global',text:'Edited global',productionRevision:3});
assert.equal(global.scenes.s.global_prompt,'Edited global');
assert.equal(global.scenes.s.prompt_edited,true);
assert.equal(global.scenes.s.chapters.a.shot_prompt,'Shot A');
drafts.clear('p','s','a');assert.equal(createPromptDrafts(storage).get('p','s','a'),null);
const {renderHandoff,createHandoffState}=await load('../static/director-page.js');
const state=createHandoffState(storage);state.select('p','s','a');
p.delivery.scenes[0].references=[];p.delivery.scenes[0].missing_references=[];
for(const c of p.delivery.scenes[0].chapters)Object.assign(c,{number:1,duration:8,title:c.shot_id,guidance:{},issues:[]});
drafts.set('p','s','a',{...d,text:'Draft </textarea><script>'});
const html=renderHandoff(p,state,{},'Astra',drafts);
assert.match(html,/Draft &lt;\/textarea&gt;&lt;script&gt;/);assert.doesNotMatch(html,/readonly/);assert.match(html,/儲存提示詞/);assert.match(html,/未儲存修改/);
console.log('Prompt editor: durable isolated drafts, conflict/empty rejection, scene/shot save scope, settings preservation and escaped editable rendering passed.');
