import assert from 'node:assert/strict';
import {renderVideoWorkflow,readyForHandoff,referenceDemandMarkup} from '../static/video-workflow.js';
import {imagePlanMarkup} from '../static/storyboard-board.js';
import {renderFrozenReferences,renderDraftPending} from '../static/video-render.js';
const demands=[{entity_id:'ada',name:'Ada',role:'character_identity',required:true,reason:'Keep coat <safe>',status:'ready',asset_id:'a',asset:{id:'a'},label:'Picture 1',subject:'Subject 1'}, {entity_id:'pip',name:'Pip',role:'character_identity',required:false,reason:'Offscreen',status:'optional_omitted'}];
const row={shot_id:'shot',scene_id:'scene',title:'Shot',duration:4,mode:'REF2VA',selected:true,frames:[],prompt:{text:'saved',source_hash:'hash'},source_hash:'hash',ready:true,reasons:[],jobs:{},conditioning:{plan:{mode:'REF2VA',reference_demands:demands,unresolved_constraints:[]}},reference_demands:demands};
const p={id:'p',production:{scenes:[{id:'scene',title:'Room'}],shots:[{id:'shot',duration:4,title:'Shot'}]},video_workflow:{shots:[row]}};
assert(readyForHandoff(p,row));
let html=renderVideoWorkflow(p,'shot',()=>'',{get:()=>null},()=>'<p>LEGACY</p>');
assert(!html.includes('LEGACY')&&html.includes('data-video-prompt'));
assert(html.includes('Picture 1')&&html.includes('角色身份')&&html.includes('可選・已略去'));
assert(!html.includes('首尾幀 fl2v')&&!html.includes('integrated_multimodal_description'));
assert(html.includes('Keep coat &lt;safe&gt;')&&!html.includes('Keep coat <safe>'));
assert(renderDraftPending(p,row,{get:(_p,id,mode)=>id==='shot'&&mode==='REF2VA'}));
row.ready=false;row.reference_demands[0].status='missing';
assert(!readyForHandoff(p,row));
html=renderVideoWorkflow(p,'shot',()=>'',{get:()=>null});
assert(/data-action="video-prompt-generate"[^>]+disabled/.test(html));
html=imagePlanMarkup({image_plan:row.conditioning.plan,reference_demands:demands,anchors:[]});
assert(html.includes('本鏡身份／外觀參考')&&!html.includes('只需來源首幀'));
html=renderFrozenReferences({request:{source:{mode:'REF2VA',reference_demands:demands}},image_inputs:[{asset_id:'a',name:'Ada',role:'character_identity',label:'Picture 1',sha256:'abc',submission_verified:true}]});
assert(html.includes('Keep coat &lt;safe&gt;')&&html.includes('graph 綁定及提交回條吻合'));
console.log('Reference demand UI, new/legacy routing, draft guard and receipt evidence passed.');
