import assert from 'node:assert/strict';
import {settingsValues,editSettings,renderSettings,suggestedSteps,canvasSize,setSettingsCatalog} from '../static/video-render-settings.js';
const turbo='minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors';
const defaults={model:'minimax_h3_fl2va_pruned_int8_convrot.safetensors',width:864,height:480,aspect_ratio:'16:9',megapixels:.4,steps:8,acceleration_lora:turbo,other_loras:[],audio_mode:'generate',attention:'kitchen',scale:1,second_pass:false,refine_steps:3,refine_denoise:.25,seed:null};
const p={id:'settings-test',video_renders:{defaults}},row={shot_id:'shot',mode:'I2VA'};
const change=(name,value)=>editSettings(p,row,{dataset:{renderSetting:name},value});
let v=settingsValues(p,row),html=renderSettings(p,row,v,false,false);
for(const label of ['加速 LoRA','Attention 運算方式','畫面比例','二採','放大倍數','Style LoRA','靜音影片'])assert(html.includes(label));
assert(!html.includes('data-render-settings open'));assert.equal(v.steps,8);
change('steps','13');assert.equal(settingsValues(p,row).steps,8);
assert(/data-render-setting="steps"[^>]*disabled/.test(html));
change('acceleration_lora','minimax_h3_fl2v_turbo_4step_v1.1.safetensors');assert.equal(settingsValues(p,row).steps,4);
change('acceleration_lora','');assert.equal(settingsValues(p,row).steps,20);
change('aspect_ratio','9:16');assert.deepEqual(canvasSize(settingsValues(p,row)),[480,864]);
change('megapixels','1');assert.deepEqual(canvasSize(settingsValues(p,row)),[768,1376]);
change('second_pass','true');change('scale','2');change('upscale_model','4x-UltraSharp.pth');
v=settingsValues(p,row);html=renderSettings(p,row,v,false,true);
assert(html.includes('二採去噪強度')&&html.includes('先放大再二採'));
change('second_pass','false');assert.equal(settingsValues(p,row).upscale_model,'');
change('audio_mode','mute');assert(renderSettings(p,row,settingsValues(p,row),false,true).includes('略過聲音解碼'));
editSettings(p,row,{dataset:{renderLoraIndex:'0'},value:'h3_detail.safetensors'});
editSettings(p,row,{dataset:{renderLoraStrength:'0'},value:'0.6'});
assert.deepEqual(settingsValues(p,row).other_loras,[{name:'h3_detail.safetensors',strength:.6}]);
assert.equal(settingsValues(p,{...row,shot_id:'different'}).steps,8);
setSettingsCatalog({loras:[{name:'minimax_h3_ref2v_turbo_8step.safetensors',family:'REF2VA',turbo:true},{name:turbo,family:'FL2VA',turbo:true},{name:'<img onerror=bad>',family:null,turbo:false}],attention:['kitchen','default'],upscale_models:['4x-UltraSharp.pth']});
html=renderSettings(p,row,settingsValues(p,row),false,true);assert(!html.includes('minimax_h3_ref2v_turbo_8step'));assert(!html.includes('<img onerror'));
assert.equal(suggestedSteps(turbo),8);assert.equal(suggestedSteps('creative.safetensors'),20);
console.log('H3 settings: defaults, locked LoRA step presets, ratio+MP, refine+scale, mute, extra LoRA strength, scoped storage and escaped installed choices passed.');
const motion='camera_motion_h3_lora_v1_3000_pruned.safetensors';
setSettingsCatalog({loras:[{name:motion,label:'運鏡 · Camera Motion',default_strength:1,recommended_strength:[.8,1],strength_basis:'author_range',trigger:'camera motion',source_url:'https://huggingface.co/Jojocodex/minimax-h3-Camera-Motion-lora'},{name:'h3-other.safetensors',default_strength:.75,recommended_strength:[.75,.75]}],attention:['default','kitchen']});
editSettings(p,row,{dataset:{renderLoraIndex:'0'},value:motion});
assert.equal(settingsValues(p,row).other_loras[0].strength,1); // new choice does not inherit previous LoRA .6
html=renderSettings(p,row,settingsValues(p,row),false,true);
assert(html.includes('運鏡 · Camera Motion'));
assert(html.includes('自動加入觸發詞')&&html.includes('檔案與來源'));
assert(!html.includes('運鏡 · Camera Motion —'));
assert(html.includes('建議 0.8–1.0')&&html.includes('camera motion</code>'));
assert(html.indexOf('Style LoRA（風格')<html.indexOf('聲音輸出'));
editSettings(p,row,{dataset:{renderLoraStrength:'0'},value:'.85'});
assert.equal(settingsValues(p,row).other_loras[0].strength,.85);
editSettings(p,row,{dataset:{renderLoraIndex:'0'},value:motion});
assert.equal(settingsValues(p,row).other_loras[0].strength,.85);
editSettings(p,row,{dataset:{renderLoraIndex:'0'},value:'h3-other.safetensors'});
assert.equal(settingsValues(p,row).other_loras[0].strength,.75);

// Acceleration is a separate purpose, even when its model family is unknown.
const legacyTurbo='minimax_h3_turbo_4step_ckpt600_ema_V4.safetensors';
setSettingsCatalog({loras:[{name:motion,purpose:'style'},{name:turbo,turbo:true,family:'FL2VA',purpose:'acceleration'},{name:legacyTurbo,turbo:false,family:null,purpose:'acceleration'}],attention:['kitchen']});
html=renderSettings(p,row,settingsValues(p,row),false,true);
const styleSection=html.match(/<section class="h3-other-loras">([\s\S]*?)<\/section>/)[1];
assert(styleSection.includes(motion));assert(!styleSection.includes(turbo)&&!styleSection.includes(legacyTurbo));
editSettings(p,row,{dataset:{renderLoraIndex:'0'},value:legacyTurbo});
const cleaned=settingsValues(p,row);assert.equal(cleaned.other_loras.length,0);
assert(renderSettings(p,row,cleaned,false,true).includes('加速權重已移除'));

const fp8='minimax_h3_fl2va_pruned_fp8_scaled.safetensors';
const refModel='minimax_h3_ref2va_pruned_int8_convrot.safetensors';
setSettingsCatalog({models:[{name:defaults.model,family:'FL2VA'},{name:fp8,family:'FL2VA'},{name:refModel,family:'REF2VA'}],loras:[],attention:['kitchen']});
const before=settingsValues(p,row);
change('model',fp8);
assert.equal(settingsValues(p,row).model,fp8);
assert.equal(settingsValues(p,row).steps,before.steps);
assert.equal(settingsValues(p,row).acceleration_lora,before.acceleration_lora);
assert.equal(settingsValues(p,{...row,shot_id:'fresh-model'}).model,defaults.model);
html=renderSettings(p,row,settingsValues(p,row),false,true);
const modelSelect=html.match(/<select data-render-setting="model"[^>]*>([\s\S]*?)<\/select>/)[1];
assert(modelSelect.includes(fp8+'" selected'));
assert(modelSelect.includes('（預設）')&&!modelSelect.includes(refModel));
setSettingsCatalog({models:[],loras:[]});
assert(renderSettings(p,row,settingsValues(p,row),false,true).includes(fp8+'（目前找不到）'));
console.log('H3 model: default, installed family filter, selection persistence, unavailable choice and unchanged LoRA steps passed.');

const refRow={shot_id:'ref-cross-model',mode:'REF2VA'};
const refP={id:'ref-model-test',video_renders:{defaults:{...defaults,model:refModel,acceleration_lora:'',steps:20}}};
const refTurbo='minimax_h3_ref2v_turbo_4step.safetensors';
setSettingsCatalog({models:[{name:defaults.model,family:'FL2VA'},{name:fp8,family:'FL2VA'},{name:refModel,family:'REF2VA'}],loras:[{name:turbo,family:'FL2VA',turbo:true},{name:refTurbo,family:'REF2VA',turbo:true}]});
html=renderSettings(refP,refRow,settingsValues(refP,refRow),false,true);
assert(html.includes(fp8)&&html.includes(refModel));
editSettings(refP,refRow,{dataset:{renderSetting:'model'},value:fp8});
html=renderSettings(refP,refRow,settingsValues(refP,refRow),false,true);
const refAccel=html.match(/<select data-render-setting="acceleration_lora"[^>]*>([\s\S]*?)<\/select>/)[1];
assert(refAccel.includes(turbo)&&!refAccel.includes(refTurbo));
assert.equal(settingsValues(refP,refRow).steps,20);
editSettings(refP,refRow,{dataset:{renderSetting:'acceleration_lora'},value:turbo});
assert.equal(settingsValues(refP,refRow).steps,8);
console.log('Ref2V: FL2VA models selectable; LoRA family follows chosen base, steps follow accelerator.');
