import assert from 'node:assert/strict';
import {renderLoraAdvice} from '../static/style-lora-advice.js';
import {installVideoRenderUI} from '../static/video-render.js';
import {settingsValues,storeSettings} from '../static/video-render-settings.js';
const model='minimax_h3_fl2va_pruned_int8_convrot.safetensors';
const row={shot_id:'s',mode:'I2VA'},p={id:'p',video_workflow:{shots:[row]},video_renders:{defaults:{model,acceleration_lora:'minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors',other_loras:[{name:'old',strength:.9}],width:864,height:480},takes:[],shots:{s:{ready:true,source_hash:'hash',style_lora_advice:{[model]:{id:'job',state:'succeeded',provider:'astra',source_hash:'hash',candidates:[],result:{summary:'不需要 <script>',decisions:[]}}}}}}};
let html=renderLoraAdvice(p,row,settingsValues(p,row),false);
assert(html.includes('不使用 Style LoRA')&&html.includes('&lt;script&gt;')&&!html.includes('<script>'));
const handlers={};globalThis.document={addEventListener:(type,fn)=>handlers[type]=fn};
let done;const calls=[];
installVideoRenderUI({getProject:()=>p,drafts:{get:()=>null},api:async(path,body)=>{calls.push({path,body});return {other_loras:[]};},modal:()=>{},refresh:async()=>{},guarded:fn=>done=fn(),toast:()=>{}});
const b={dataset:{renderAction:'apply-lora-advice',id:'s'},textContent:'套用建議',disabled:false,closest:()=>null};
handlers.click({target:{closest:()=>b}});await done;
assert.deepEqual(settingsValues(p,row).other_loras,[]);
assert.equal(settingsValues(p,row).steps,8);
assert(calls[0].path.endsWith('/lora-advice-selection'));
p.video_renders.shots.s.source_hash='changed';html=renderLoraAdvice(p,row,settingsValues(p,row),false);
assert(html.includes('請重新推薦')&&!html.includes('data-render-action="apply-lora-advice"'));
console.log('Style advice: none/apply, source expiry, escaping and preservation of accelerator/steps passed.');
