import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const {workItems,workSummary,stageActivity,workAction,workState,renderWorkActivity,renderWorkRow}=await import(url(readFileSync('static/work-activity.js','utf8')));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,attrs='',cls='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const helpers={esc,button,displayLabel:x=>x,targetName:id=>id};
const base={id:'p',title:'作品',revision:2,production:{canon:[{id:'c'}],shots:[{id:'s',keyframes:[{id:'f'}]}]},assets:[],jobs:[],video_renders:{takes:[]},postproduction:{takes:[]}};
const queued={id:'q',capability:'storyboard',target_id:'<img src=x>',state:'queued',created:'2026-09-13T00:00:00Z',queue:{label:'長篇分鏡',position:2,running:1,running_projects:['其他作品']}};
const running={id:'r',capability:'director_style',state:'running',progress:{kind:'chapter_stages',label:'正在整理原文',completed:3,total:8,completed_shots:1,total_shots:4}};
const p={...base,jobs:[queued,running,{id:'image',capability:'image',target_id:'c',state:'queued'},{id:'manual',capability:'custom',state:'awaiting_input'},{id:'bad',state:'failed',error:'<script>bad</script>',updated:'2026-09-13T04:00:00Z'},{id:'done',state:'succeeded',updated:'2026-09-13T03:00:00Z'},{id:'cancel',state:'cancelled',updated:'2026-09-13T02:00:00Z'},{id:'foreign',project_id:'another',state:'running'}],video_renders:{takes:[{id:'v',shot_id:'s',state:'submitted'}]},postproduction:{takes:[{id:'voice',state:'running',entity_id:'c'}]}};
const html=renderWorkActivity(p,helpers);
for(const text of ['佇列第 2 位','其他作品','尚未開始','階段 3／8','鏡頭 1／4','等待你提交','&lt;img','聲音製作','影片生成','data-section="render"'])assert(html.includes(text),text);
for(const text of ['最近結果','較早結果','data-work-id="job:bad"','data-work-id="job:done"','data-work-id="job:cancel"'])assert(!html.includes(text),text);
assert(renderWorkRow(p.jobs.find(j=>j.id==='bad'),helpers).includes('&lt;script'));
assert(renderWorkRow(p.jobs.find(j=>j.id==='done'),helpers).includes('完成狀態不代表已採用'));
assert(renderWorkRow(p.jobs.find(j=>j.id==='cancel'),helpers).includes('已取消'));
assert(!html.includes('foreign'));assert(!html.includes('<img'));assert(!html.includes('<script>'));
assert.equal(stageActivity(p)[1].status,'1 項處理中 · 1 項排隊中');assert.equal(stageActivity(p)[2].status,'1 項排隊中');assert.equal(stageActivity(p)[4].job.id,'v');assert.equal(stageActivity(p)[5].job.id,'voice');
assert.equal(workState({...queued,cancel_requested:true}),'正在取消');
assert.equal(workSummary([{state:'awaiting_input'}]),'1 項等你處理');
assert.equal(workSummary([{state:'succeeded'}]),'目前沒有工作排隊或處理中');
assert.equal(workItems(p).length,9);
const guideSource=readFileSync('static/production-guide.js','utf8').replace("'./production-progress.js'",JSON.stringify(url(readFileSync('static/production-progress.js','utf8'))));
const {renderProductionGuide,renderProductionDashboard}=await import(url(guideSource));
const h={...helpers,stageActivity:stageActivity(p),workAction,workActivity:html};
const guide=renderProductionGuide(p,'progress',h),dashboard=renderProductionDashboard(p,h);
assert(guide.indexOf('data-work-activity')<guide.indexOf('class="production-path"'));
assert(dashboard.includes('1 項處理中 · 1 項排隊中'));assert(dashboard.includes('查看本步工作'));assert(dashboard.includes('data-id="q"'));
// Run the actual focus-safe polling function with deferred transport. It may only
// update status surfaces and must ignore responses after changing projects.
const source=readFileSync('static/app.js','utf8');
const block=source.slice(source.indexOf('let progressPolling='),source.indexOf('function updateWorkSurfaces('));
const updates=[],queries=[];let release;
const ctx={project:{id:'p',jobs:['original'],assets:['original']},projectLoadVersion:0,refreshing:false,api:()=>new Promise(r=>release=r),updateWorkSurfaces:x=>updates.push(x),document:{querySelectorAll:s=>{queries.push(s);return [];}}};
vm.createContext(ctx);vm.runInContext(block,ctx);
const first=vm.runInContext('updateVisibleImageProgress()',ctx);await vm.runInContext('updateVisibleImageProgress()',ctx);assert.equal(updates.length,0);
release({id:'p',jobs:['fresh'],assets:[]});await first;assert.equal(updates.length,1);assert.deepEqual(ctx.project.jobs,['original'],'polling must not replace editable state');
const stale=vm.runInContext('updateVisibleImageProgress()',ctx);ctx.projectLoadVersion++;release({id:'p'});await stale;assert.equal(updates.length,1,'ignore even same-project navigation race');
assert(!queries.some(q=>q.includes('textarea')||q.includes('audio')||q.includes('video')),'polling only touches status containers');
assert(source.includes("busy||$('#modal-root').children.length"),'status polling remains active during requests and dialogs');
console.log('Work activity: queues, actual stages, all work types, terminal states, escaping, stage cards, coalescing, draft preservation and stale response protection passed.');
