import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {renderHandoff,createHandoffState}=await import('data:text/javascript;base64,'+Buffer.from(readFileSync('static/director-page.js','utf8')).toString('base64'));
const shared=[{asset_id:'person',name:'主角',label:'Picture 1'},{asset_id:'room',name:'樓梯',label:'Picture 2'}];
const prop={asset_id:'jug',name:'五公升膠水樽',label:'Picture 3',subject:'Subject 3',role:'prop'};
const chapter=(id,local)=>({shot_id:id,title:id,number:id==='one'?1:2,duration:10,shot_prompt:'summary: [reference generation]',references:[...shared,...local],local_references:local,missing_references:[],issues:[],guidance:{continuityFromPrev:false,notes:''}});
const p={id:'project',delivery:{configuration:{context_frames:22,continuity_enabled:false},scenes:[{scene_id:'scene',title:'Scene',global_prompt:'subject_definitions: common',references:shared,missing_references:[],chapters:[chapter('one',[prop]),chapter('two',[])]}]}};
const state=createHandoffState();
assert(!renderHandoff(p,state).includes('五公升膠水樽'));
state.select('project','scene','one');let html=renderHandoff(p,state);
assert(html.includes('五公升膠水樽')&&html.includes('Picture 3 · 本 Shot'));
assert(html.includes('Scene 共用 2 張 ＋ 本 Shot 1 張道具'));
assert(html.includes('data-action="send-comfy" data-id="jug"'));
assert(html.includes('保留公共圖片槽位')&&html.includes('清掉上一鏡'));
state.select('project','scene','two');html=renderHandoff(p,state);
assert(!html.includes('五公升膠水樽')&&html.includes('本 Shot 0 張道具'));
p.delivery.scenes[0].chapters[1].missing_references=['螺絲批'];
assert(renderHandoff(p,state).includes('本 Shot 尚欠道具參考圖：螺絲批'));
prop.name='<script>bad</script>';state.select('project','scene','one');
assert(!renderHandoff(p,state).includes('<script>bad</script>'));
console.log('Shot refs: shared exclusion, local slot labels/actions/counts, absent props, missing refs and escaping passed.');
