import assert from 'node:assert/strict';
import {renderGenerationGroups,installGenerationGroups} from '../static/generation-groups.js';
import {renderVideoProduction,installVideoRenderUI} from '../static/video-render.js';
import {createPromptDrafts} from '../static/prompt-editor.js';
const gid='mg_aaaaaaaaaaaaaaaa',drafts=createPromptDrafts();
const row={id:gid,shot_id:gid,kind:'generation_group',title:'Discovery <script>',reason:'Read then react',members:[{title:'View',start:0,end:3,source_in:0,shot:{framing:'CU',angle:'Eye-level',action:'Read',keyframes:[]},edit:{}}],duration:6,mode:'REF2VA',source_hash:'b'.repeat(64),references:[],reference_requirements:[{target_id:'ada',title:'Ada',role:'character',ready:false}],reasons:['Prepare Ada'],prompt:{},checks:['Check actual cut']};
const p={workflow_contract_version:1,id:'test',production:{scenes:[{id:'scene',title:'Workshop'}],edit_plan:[]},generation_groups:{revision:0,rows:[row]},video_workflow:{shots:[]},video_renders:{defaults:{},defaults_by_mode:{REF2VA:{}},shots:{},groups:{[gid]:{ready:true,source_hash:'a'.repeat(64),reasons:[],timing:{duration:6,frame_count:158,aligned_duration:158/24}}},takes:[]}};
let html=renderGenerationGroups(p,drafts);
assert(html.includes('建立多鏡分組')&&html.includes('由導演安排：Workshop'));
assert(html.includes('準備此參考圖')&&html.includes('data-target="ada"'));
assert(html.includes('一鍵生成本組影片')&&!html.includes('<script>'));
assert(html.includes('採用不等於已核對切點'));
const handlers={},calls=[];let pending;
globalThis.document={addEventListener:(type,fn)=>handlers[type]=fn,querySelectorAll:()=>[]};
installVideoRenderUI({getProject:()=>p,drafts,api:async(path,body)=>{calls.push({path,body});return {id:'f'.repeat(16),state:'queued'};},modal:()=>{},refresh:async()=>{},guarded:fn=>pending=fn(),toast:()=>{}});
handlers.click({target:{closest:()=>({disabled:false,dataset:{renderAction:'freeze',id:gid}})}});await pending;
assert(calls[0].path.endsWith('/freeze'));
handlers.click({target:{closest:()=>({disabled:false,dataset:{renderAction:'generate',id:gid}})}});await pending;
assert.equal(calls[1].path,`/projects/test/video-workflow/${gid}/generate`);assert.equal(calls[1].body.frozen_id,'f'.repeat(16));
assert.equal(calls[0].body.source_hash,'a'.repeat(64));
p.video_renders.takes=[{id:'t',shot_id:gid,state:'uncertain',created:'2026-09-13T00:00:00Z',current:true}];
assert(/data-render-action="generate"[^>]*disabled/.test(renderVideoProduction(p,row,drafts)));
p.video_renders.takes=[];
installGenerationGroups({getProject:()=>p,api:async(path,body)=>{calls.push({path,body});return {};},modal:()=>{},close:()=>{},refresh:async()=>{},guarded:fn=>pending=fn(),toast:()=>{}});
handlers.click({target:{closest:()=>({disabled:false,dataset:{groupAction:'plan',id:'scene'}})}});await pending;
assert.equal(calls.at(-1).body.capability,'h3_group_plan');
handlers.click({target:{closest:()=>({disabled:false,dataset:{groupAction:'generate-prompt',id:gid}})}});await pending;
assert.deepEqual(calls.at(-1).body,{capability:'h3_video_prompt',target_id:gid});
console.log('Generation groups: storyboard/reference roles, source-hash routing, native group rendering, unresolved guard and planning/prompt actions passed.');
const {productionProgress}=await import('../static/production-progress.js');
const shots=[{id:'s1',dialogue:[]},{id:'s2',dialogue:[]}];
const progressProject={id:'test',production:{shots,canon:[],edit_plan:[{id:'e1',shot_id:'s1'},{id:'e2',shot_id:'s2'}]},assets:[],jobs:[],video_workflow:{shots:[]},generation_groups:{rows:[{...row,edit_ids:['e1','e2'],reasons:[]}]},video_renders:{shots:{},groups:{[gid]:{ready:true}},takes:[{id:'take',shot_id:gid,state:'succeeded',selected:true,current:true,mapping:{status:'planned',boundaries:[{edit_id:'e1'},{edit_id:'e2'}]}}]}};
let progress=productionProgress(progressProject);
assert.equal(progress.next.id,gid);assert.equal(progress.stages[3].done,0);
progressProject.video_renders.takes[0].mapping.status='user_observed';progress=productionProgress(progressProject);
assert.equal(progress.stages[3].done,2);assert.equal(progress.currentStage,5);
assert.equal(progressProject.video_renders.takes.length,1);
console.log('Group progress: planned cuts do not imply shot coverage; observed selected group covers edit uses without duplicating take selections.');
