import assert from 'node:assert/strict';
import {renderVideoWorkflow,strategyMarkup} from '../static/video-workflow.js';
const strategy={mode:'I2VA',reason:'Opening composition suffices.',evidence:['<script>unsafe</script>'],start_blueprint:'Ada left',end_blueprint:'',checks:['Hand','Gaze']};
assert(!strategyMarkup(strategy).includes('<script>'));
const frame={moment:'start',frame_id:'start',description:'Ada left',asset:null,ready:false};
const row={shot_id:'shot',scene_id:'scene',title:'Shot <one>',duration:6,mode:'I2VA',selected:false,frames:[frame],prompt:{},source_hash:'hash',ready:false,reasons:['首幀尚未完成並批准'],jobs:{}};
const p={id:'p',production:{scenes:[{id:'scene',title:'Room'}],shots:[{id:'shot',duration:6,title:'Shot <one>'}]},video_workflow:{shots:[row]}};
const drafts={get:()=>null};
let html=renderVideoWorkflow(p,'shot',()=>'',drafts);
assert(html.includes('data-video-scene'));
assert(html.includes('data-mode="I2VA" aria-pressed="true"'));
assert(html.includes('生成此模式提示詞'));
assert(/data-action="video-prompt-generate"[^>]+disabled/.test(html));
assert(!html.includes('data-action="video-copy"'));
assert(html.includes('Shot &lt;one&gt;'));
row.ready=true;row.frames[0]={...frame,ready:true,asset:{id:'real-id',review:{verdict:'revise',issues:['wrong hand']}}};row.prompt={text:'current'};
html=renderVideoWorkflow(p,'shot',()=>'<a>real image</a>',drafts);
assert(html.includes('data-action="video-copy"')&&html.includes('wrong hand'));
row.mode='REF2VA';html=renderVideoWorkflow(p,'shot',()=>'',drafts,r=>'<section>EMBEDDED '+r.shot_id+'</section>');
assert(html.includes('EMBEDDED shot')&&!html.includes('data-action="video-ref"')&&!html.includes('data-video-prompt'));
console.log('Video workflow modes, readiness, review and escaping checks passed.');
row.mode='FL2VA';row.ready=false;row.jobs={h3_video_prompt:{id:'job',state:'succeeded',result:{text:'',frame_issues:['Fix the mismatched endpoint.']}}};
html=renderVideoWorkflow(p,'shot',()=>'',drafts);
assert(html.includes('圖片差異提醒')&&html.includes('Fix the mismatched endpoint.')&&!html.includes('data-action="video-copy"'));
console.log('Frame conflict display and handoff gating passed.');

row.jobs.h3_video_prompt.result.text='integrated_multimodal_description: Full prompt';
html=renderVideoWorkflow(p,'shot',()=>'',drafts);
assert(html.includes('完整 H3 提示詞 · 新版待採用')&&html.includes('採用並複製完整提示詞'));
assert(html.includes('readonly')&&html.includes('Full prompt'));
console.log('Full candidate shown inline with adopt-and-copy control.');

row.selected=true;row.strategy={result:strategy};row.jobs.h3_strategy={id:'plan',state:'succeeded',adopted:true,result:strategy};
html=renderVideoWorkflow(p,'shot',()=>'',drafts);
assert.equal((html.match(/data-action="video-mode"[^>]*disabled/g)||[]).length,3);
assert.equal((html.match(/locked-out/g)||[]).length,2);
assert(html.includes('已鎖定')&&html.includes('Opening composition suffices.')&&html.includes('重新生成建議'));
assert(html.includes('video-current-strategy'));
row.jobs.h3_strategy.adopted=false;
html=renderVideoWorkflow(p,'shot',()=>'',drafts);
assert(html.includes('待採用')&&html.includes('data-action="video-review" data-id="plan"'));
console.log('Locked modes and inline recommendation states passed.');
