import assert from 'node:assert/strict';
import {renderGroupPlanReview,installGenerationGroups} from '../static/generation-groups.js';
import {jobDetailBody,refreshJobDetail} from '../static/job-detail.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,attrs='')=>`<button data-action="${action}" ${attrs}>${label}</button>`;
const helpers={esc,button,providerName:x=>x,renderProductionMethod:()=>'',renderContextUsage:()=>'',imageLoraMarkup:()=>''};
const result={summary:'OLD BAD ADVICE <script>',groups:[{title:'Old REF2VA suggestion',edit_ids:['e'],execution:'separate_source',mode:'REF2VA',reference_targets:[],reason:'Incorrect trim reasoning',checks:['Inspect pixels']}]};
const j={id:'j',project_id:'p',target_id:'scene',capability:'h3_group_plan',state:'succeeded',result,contract_current:false,stale:true};
const p={id:'p',production:{shots:[{id:'s',title:'Switch <img>'}],edit_plan:[{id:'e',shot_id:'s'}]},generation_groups:{revision:0,rows:[],plans:[j]}};
let html=renderGroupPlanReview(p,j);
assert(html.includes('需要重新安排'));assert(html.includes('data-group-action="plan" data-id="scene"'));
assert(/id="group-plan-adopt"[^>]*disabled/.test(html));assert(html.indexOf('<details>')<html.indexOf('OLD BAD ADVICE'));
assert(html.includes('data-action="video-ref" data-id="s"'));assert(!html.includes('<img>')&&!html.includes('<script>'));
assert(html.includes('首尾圖不能保證'));
const modern={...j,result:{...result,summary:'Three independent sources.',groups:result.groups.map(g=>({...g,title:'Independent source',mode:null}))},contract_current:true,stale:false};
html=renderGroupPlanReview(p,modern);
assert(!/id="group-plan-adopt"[^>]*disabled/.test(html));assert(!html.includes('undefined'));
assert(html.includes('生成模式由逐鏡影片準備判斷'));assert(!html.includes('重新安排此場景'));
assert(/id="group-plan-adopt"[^>]*disabled/.test(renderGroupPlanReview(p,{...modern,stale:true})));
html=jobDetailBody({...j,input:{group_plan_source:{}}},p,helpers);
assert(html.includes('舊版生成安排需要更新'));assert(html.indexOf('需要重新安排')<html.indexOf('OLD BAD ADVICE'));
assert(html.indexOf('<details>')<html.indexOf('OLD BAD ADVICE'));assert(!html.includes('<script>'));
const body={_jobSnapshot:{...j,input:{group_plan_source:{}}},ownerDocument:{activeElement:null},contains:()=>false,querySelectorAll:()=>[],innerHTML:''};
refreshJobDetail(body,{...j,input:{revision:2}},p,helpers);assert(body.innerHTML.includes('舊版生成安排需要更新'));
assert(jobDetailBody({...modern,input:{group_plan_source:{plan_contract_version:3}}},p,helpers).includes('生成安排待檢視'));
assert(jobDetailBody({...modern,input:{group_plan_source:{plan_contract_version:2}}},p,helpers).includes('舊版生成安排需要更新'));
const handlers={},el={},calls=[];let pending;
globalThis.document={addEventListener:(type,fn)=>handlers[type]=fn,querySelector:selector=>selector==='#group-plan-adopt'?el:null};
installGenerationGroups({getProject:()=>p,api:async(...args)=>calls.push(args),modal:()=>{},close:()=>{},refresh:async()=>{},guarded:fn=>pending=fn(),toast:()=>{}});
handlers.click({target:{closest:()=>({disabled:false,dataset:{groupAction:'plan-review',id:'j'}})}});await pending;
el.onclick();await pending;assert.equal(calls.length,0,'legacy cannot invoke adoption even when handler is called directly');
p.generation_groups.plans=[modern];
handlers.click({target:{closest:()=>({disabled:false,dataset:{groupAction:'plan-review',id:'j'}})}});await pending;
el.onclick();await pending;assert.equal(calls[0][0],'/projects/p/generation-groups/plan-adopt/j');
console.log('Planner contract UI: historical advice collapsed and blocked, independent mode ownership, source navigation, escaping, polling provenance and adoption handlers passed.');
