import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {renderVideoWorkflow} from '../static/video-workflow.js';
import {renderHandoff,createHandoffState} from '../static/director-page.js';
import {createPromptDrafts} from '../static/prompt-editor.js';
const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
const state=createHandoffState(storage),drafts=createPromptDrafts(storage);
const chapter=(id,n)=>({shot_id:id,title:id,number:n,duration:8,shot_prompt:'summary: '+id,issues:[],local_references:[],guidance:{continuityFromPrev:false,reason:'A deliberate cut.',notes:''}});
const scenes=[{scene_id:'a',title:'Scene A',global_prompt:'subject_definitions: A',references:[],missing_references:[],chapters:[chapter('one',1),chapter('two',2)]},{scene_id:'b',title:'Scene B',global_prompt:'subject_definitions: B',references:[],missing_references:[],chapters:[chapter('three',3)]}];
const rows=scenes.flatMap(s=>s.chapters.map(c=>({...c,scene_id:s.scene_id,mode:'REF2VA',prompt:{},frames:[],jobs:{},ready:false,reasons:[]})));
const p={id:'p',production:{scenes:scenes.map(s=>({id:s.scene_id,title:s.title})),shots:rows.map(r=>({id:r.shot_id,title:r.title,duration:r.duration}))},video_workflow:{shots:rows},delivery:{scenes,configuration:{context_frames:22,continuity_enabled:true},guidance_review:{status:'ready'}}};
const render=id=>renderVideoWorkflow(p,id,()=>'',drafts,row=>renderHandoff(p,state,{},'Astra',drafts,{sceneId:row.scene_id,shotId:row.shot_id}));
state.select('p','a','shared');let html=render('two');
assert(html.includes('subject_definitions: A'));
assert.equal((html.match(/<textarea /g)||[]).length,1);
assert.equal((html.match(/<h1>/g)||[]).length,1);
assert(!html.includes('data-director-scene')&&!html.includes('data-action="video-ref"'));
assert(!/data-action="director-step"[^>]*data-step="one"/.test(html));
assert(/data-action="director-step"[^>]*data-step="two"/.test(html));
state.select('p','a','two');drafts.set('p','a','two',{text:'MY SHOT DRAFT'});html=render('two');
assert(html.includes('MY SHOT DRAFT')&&html.includes('data-action="director-save"')&&html.includes('複製分鏡提示詞')&&html.includes('A deliberate cut.'));
assert(!html.includes('subject_definitions: A'));
html=render('three');assert(!html.includes('MY SHOT DRAFT')&&html.includes('summary: three'));
rows[1].mode='I2VA';html=render('two');assert(!html.includes('director-embedded')&&!html.includes('MY SHOT DRAFT'));
rows[1].mode='REF2VA';assert(render('two').includes('MY SHOT DRAFT'));
const app=readFileSync('static/app.js','utf8');const context={location:{hash:'#h3'}};vm.createContext(context);
vm.runInContext(app.slice(app.indexOf('function routePage(){'),app.indexOf('let projects=')),context);
assert.equal(context.routePage(),'video');context.location.hash='#h3-legacy';assert.equal(context.routePage(),'video');
const nav=readFileSync('static/production-guide.js','utf8').split('export function renderProductionNav')[1].split('export function renderProductionGuide')[0];assert(!nav.includes("['h3',"));assert.equal((nav.match(/\['video',/g)||[]).length,1);
// A deep link must not keep restoring an old project/Shot after normal UI selection.
const route={URL,location:{href:'http://127.0.0.1:4760/?project=old&shot=oldshot#video'},window:{history:{replaceState(_a,_b,url){route.location.href='http://127.0.0.1:4760'+url;}}}};
vm.createContext(route);vm.runInContext(app.slice(app.indexOf('function updateProjectURL('),app.indexOf('function selectVideoShot(')),route);
route.updateProjectURL('new','overview');let url=new URL(route.location.href);
assert.equal(url.searchParams.get('project'),'new');assert.equal(url.searchParams.get('shot'),null);assert.equal(url.hash,'#overview');
route.updateProjectURL('new','video','later');url=new URL(route.location.href);
assert.equal(url.searchParams.get('shot'),'later');assert.equal(url.hash,'#video');
console.log('Unified video: one sidebar/page/Shot selector; mode-specific content; scoped Scene/Shot tabs; preserved drafts; legacy routes passed.');
