import assert from 'node:assert/strict';
import {renderStoryboard,renderBoardPlan,installStoryboard} from '../static/storyboard-board.js';
import {productionProgress} from '../static/production-progress.js';
const a={id:'p1',frame_id:'f1',time:2,purpose:'Read <evidence>',frame:{description:'A hand on the switch'},asset:{id:'a1'},candidates:[{id:'a1',status:'approved',token:'t1'}],ready:false};
const scene={scene_id:'s1',title:'Workshop',summary:'Read then react',adopted:true,ready:false,panels:[{title:'View',reason:'Reveal switch',edit_id:'e1',shot_id:'shot',edit:{planned_edit_in:2,planned_edit_out:6},anchors:[a]}]};
const p={id:'test',revision:1,storyboard:{revision:2,scenes:[scene]},production:{scenes:[{id:'s1'}],shots:[{id:'shot',title:'View',dialogue:[]}],canon:[],edit_plan:[{id:'e1',shot_id:'shot'}]},assets:[{id:'a1',status:'approved',review:{verdict:'revise',issues:['Wrong hand <script>']}}],jobs:[],video_workflow:{shots:[]},video_renders:{takes:[],shots:{}}};
const html=renderStoryboard(p);
assert(html.includes('跟剪接次序睇畫面')&&html.includes('2 秒')&&html.includes('0／1'));
assert(html.includes('&lt;evidence&gt;')&&!html.includes('<evidence>'));
assert(html.includes('data-board-action="review"')&&html.includes('data-board-action="batch"'));
assert.equal(productionProgress(p).next.page,'shots');
const candidate={state:'succeeded',result:{summary:'Complete board',panels:[{edit_id:'e1',reason:'Read it',anchors:[{time:2,purpose:'Read',description:'Hand','reuse_frame_id':''}]}]}};
assert(renderBoardPlan(p,scene,candidate).includes('新增指定時刻畫面'));
const handlers={},calls=[];let form,pending,markup='';
globalThis.document={addEventListener:(type,fn)=>handlers[type]=fn,querySelector:()=>form};
const button={disabled:false};
form={elements:{asset_id:{value:'a1'},note:{value:'Eyeline checked'}},querySelectorAll:()=>[],querySelector:()=>({innerHTML:''})};
installStoryboard({getProject:()=>p,getSettings:()=>({}),api:async(path,body)=>{calls.push({path,body});return {};},modal:(title,body)=>{markup=body;},close:()=>{},refresh:async()=>{},guarded:fn=>pending=fn(),toast:()=>{}});
handlers.click({target:{closest:()=>({disabled:false,dataset:{boardAction:'review',scene:'s1',id:'p1'}})}});await pending;
assert(markup.includes('批准這格及圖片'));
form.onsubmit({preventDefault(){},submitter:{value:'approved'}});await pending;
assert.deepEqual(calls.at(-1),{path:'/projects/test/storyboard/s1/review/p1',body:{revision:2,token:'t1',asset_id:'a1',verdict:'approved',note:'Eyeline checked'}});
form={elements:{feedback:{value:'Add prop anchor'}},querySelector:()=>button};
handlers.click({target:{closest:()=>({disabled:false,dataset:{boardAction:'plan',scene:'s1'}})}});await pending;
form.onsubmit({preventDefault(){}});await pending;
assert.deepEqual(calls.at(-1).body,{capability:'storyboard_frames',target_id:'s1',feedback:'Add prop anchor'});
// A later failed attempt must not hide an earlier usable plan (live deadlock regression).
const c1={id:'c1',state:'succeeded',stale:false,adopted:false,usable:true,created:'2026-09-14T15:44:54+00:00'};
const c2={id:'c2',state:'failed',stale:false,adopted:false,usable:false,created:'2026-09-14T15:47:20+00:00',error:'用圖需要須引用本鏡已有導演資料作依據。'};
const scene2={...scene,candidates:[c2,c1],job:{id:'c2',state:'failed',error:c2.error,result:null,stale:false,adopted:false}};
const p2={...p,storyboard:{revision:3,scenes:[scene2]}};
const html2=renderStoryboard(p2);
assert(html2.includes('data-id="c1"')&&html2.includes('檢視較早方案'),'an earlier usable plan must stay reachable after a failed retry');
assert(html2.includes('最新一次失敗唔會蓋過佢'));
let planMarkup='',planCalls=[];
installStoryboard({getProject:()=>p2,getSettings:()=>({}),api:async(path,body)=>{planCalls.push({path,body});return path.startsWith('/jobs/')?{id:'c1',state:'succeeded',result:{summary:'Earlier usable plan',panels:[{edit_id:'e1',reason:'Read it',image_plan:{mode:'I2VA',reason:'Source opening is enough.',evidence:[],unresolved_constraints:[]},anchors:[{time:0,reuse_frame_id:'f1',purpose:'Open on the switch',description:'A hand near the switch'}]}]}}:{};},modal:(title,body)=>{planMarkup=body;},close:()=>{},refresh:async()=>{},guarded:fn=>pending=fn(),toast:()=>{}});
handlers.click({target:{closest:()=>({disabled:false,dataset:{boardAction:'plan-review',scene:'s1',id:'c1'}})}});await pending;
assert.equal(planCalls.at(-1).path,'/jobs/c1');
assert(planMarkup.includes('Earlier usable plan')&&planMarkup.includes('採用圖板安排'));
console.log('Visual storyboard: ordered grid, escaping, progress routing, routed planning, image-token review submission, earlier-candidate recovery and by-id plan review passed.');
