import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const src=readFileSync('static/production-progress.js','utf8');
const {productionProgress:state}=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
const blank={source_kind:'outline',assets:[],jobs:[]};
assert.equal(state(blank).next.action,'new-chapter');
assert.equal(state({...blank,story_chapters:[{id:'c'}]}).next.section,'overview-chapters');
for(const status of ['running','awaiting_input','failed','interrupted'])assert.equal(state({...blank,jobs:[{id:'j',state:status,capability:'storyboard'}]}).next.action,'job-detail');
assert.equal(state({...blank,jobs:[{id:'j',state:'succeeded',capability:'storyboard',result:{}}]}).next.action,'proposal');
const p={revision:3,production:{canon:[{id:'person',name:'Person',kind:'character'},{id:'voice',kind:'voice'}],shots:[{id:'s1',keyframes:[{id:'start'},{id:'end'}]},{id:'s2',keyframes:[]}]},assets:[{id:'orphan',target_id:'old',status:'approved'},{id:'a',target_id:'person',status:'stale'}],jobs:[]};
assert.equal(state(p).stages[1].done,0);assert.equal(state(p).stages[1].total,1);
assert.equal(state(p).currentStage,2);assert.equal(state(p,2).next.page,'review');
p.assets.push({id:'b',target_id:'person',status:'approved'},{id:'c',target_id:'person',status:'approved'});
assert.equal(state(p).stages[1].done,1);
assert.equal(state(p).next.id,'s1');assert.equal(state(p).currentStage,3);
p.jobs=[{id:'old',state:'succeeded',capability:'narrative',input:{revision:1},result:{}}];
assert.equal(state(p).currentStage,3,'old successful jobs must not send an adopted project backwards');
p.jobs.push({id:'new',state:'succeeded',capability:'narrative',input:{revision:3},result:{}});
assert.equal(state(p).next.id,'new','same-revision candidate offers review without adopting');
p.directing={proposals:{new:{required:true,state:'succeeded',result:{verdict:'revise'}}}};
assert.match(state(p).next.title,/需要修訂/,'failed creative QC explains the actual next task');
p.jobs.push({id:'revision-in-progress',state:'running',capability:'narrative',input:{revision:3},created:'2026-09-13'});
assert.equal(state(p).next.id,'revision-in-progress','new in-flight revisions must not point back to the previous candidate');
p.jobs.at(-1).state='interrupted';assert.equal(state(p).next.action,'job-detail','current interrupted revision retains its recovery entry');
p.jobs=[];
p.video_workflow={shots:[{shot_id:'s1',mode:'I2VA',selected:true,frames:[{frame_id:'start',ready:true}],references:[{target_id:'person',ready:false}],ready:true}]};
assert.equal(state(p).currentStage,2,'backend missing/stale file readiness overrides approved status');
p.video_workflow.shots[0].references[0].ready=true;
assert.equal(state(p).currentStage,3,'workflow ready does not override authoritative render check');
p.video_renders={shots:{s1:{ready:true}},takes:[]};
assert.equal(state(p).currentStage,4,'I2VA ignores unused end frame');
assert.equal(state(p).stages[2].done,1);
const row=p.video_workflow.shots[0];
row.selected=false;assert.equal(state(p).currentStage,3);
row.selected=true;row.strategy_stale=true;assert.equal(state(p).currentStage,3);
row.strategy_stale=false;row.mode='FL2VA';row.frames.push({frame_id:'end',ready:false});assert.equal(state(p).currentStage,3,'FL2VA requires the end frame');
row.mode='REF2VA';row.frames=[{frame_id:'start',ready:false}];assert.equal(state(p).currentStage,4,'REF2VA never requires a storyboard frame');
p.video_renders.shots.s1.ready=false;p.video_renders.shots.s1.reasons=['缺少指定道具參考'];
assert.match(state(p).next.description,/缺少指定道具參考/);assert.equal(state(p).stages[2].done,0);
p.video_renders.shots.s1.ready=true;
p.video_renders.takes=[{shot_id:'s1',state:'succeeded',current:true,selected:false}];
assert.match(state(p).next.title,/待你採用/);
p.video_renders.takes=[{shot_id:'s1',state:'recoverable'}];assert.match(state(p).next.title,/回收/);assert.equal(state(p).work.length,1);
p.video_renders.takes=[{shot_id:'s1',state:'running'}];assert.match(state(p).next.title,/正在/);
p.video_renders.takes=[{shot_id:'s1',state:'succeeded',current:true,selected:true},{shot_id:'s1',state:'succeeded',current:true,selected:true},{shot_id:'deleted',state:'succeeded',current:true,selected:true},{shot_id:'s2',state:'succeeded',current:false,selected:true}];
assert.equal(state(p).stages[3].done,1);assert.equal(state(p).next.id,'s2');
p.video_renders.takes.push({shot_id:'s2',state:'succeeded',current:true,selected:true});
assert.equal(state(p).currentStage,5);assert.equal(state(p).stages[4].complete,false);assert.match(state(p).next.description,/不代表/);
p.jobs=[{id:'sound',capability:'voice_defaults',state:'running'},{id:'old-failure',state:'failed'}];p.postproduction={takes:[{id:'take',state:'queued'}]};
assert.equal(state(p).work.length,2,'include current voice work, exclude historical failures');
assert.equal(state(blank).stages[2].complete,false,'0/0 is never empty-project completion');
console.log('Production progress: empty, pending, running, failed, current proposal, stale references, mode-specific frames, authoritative readiness, video review/recovery, unique adopted takes and honest editorial state passed.');

const planned={id:'p',production:{scenes:[{id:'scene',title:'Scene'}],canon:[],shots:[{id:'s',scene_id:'scene'}],edit_plan:[{id:'edit',shot_id:'s'}]},generation_groups:{arrangements:[],plans:[],rows:[]},assets:[],jobs:[]};
assert.equal(state(planned).currentStage,2);assert.equal(state(planned).next.page,'video');assert(!state(planned).stages[1].complete);
planned.generation_groups.arrangements=[{scene_id:'scene',status:'current',items:[]}];
planned.edit_segments={complete:true,segments:[{edit_id:'edit',status:'current',material:{take_id:'take'}}]};
planned.video_renders={shots:{s:{ready:false}},takes:[{id:'take',shot_id:'s',state:'succeeded',review_status:'accepted',current:true,selected:false,used_in_edit:true}]};
assert.equal(state(planned).currentStage,5,'explicit edit use works without a source selection or fresh generation readiness');
