import assert from 'node:assert/strict';
import {renderVideoProduction,renderDraftPending,installVideoRenderUI} from '../static/video-render.js';
import {createPromptDrafts} from '../static/prompt-editor.js';
const drafts=createPromptDrafts(),row={shot_id:'shot',scene_id:'scene',mode:'I2VA',title:'Shot <one>'};
const p={workflow_contract_version:1,id:'project',video_workflow:{shots:[row]},video_renders:{defaults:{width:864,height:480,steps:20,seed:null},shots:{shot:{ready:true,source_hash:'a'.repeat(64),reasons:[]}},takes:[]}};
let html=renderVideoProduction(p,row,drafts);
assert(html.includes('一鍵生成本鏡影片'));
assert(/data-render-action="generate"[^>]+disabled/.test(html),'requires explicit freeze first');
assert(html.includes('凍結本次 H3 請求'));
drafts.set('project','shot','I2VA',{text:'unsaved'});
assert(renderDraftPending(p,row,drafts));
assert(/data-render-action="generate"[^>]+disabled/.test(renderVideoProduction(p,row,drafts)));
drafts.clear('project','shot','I2VA');
row.mode='REF2VA';drafts.set('project','scene','shared',{text:'unsaved global'});
assert(renderDraftPending(p,row,drafts));drafts.clear('project','scene','shared');
drafts.set('project','scene','shot',{text:'unsaved local'});assert(renderDraftPending(p,row,drafts));
drafts.clear('project','scene','shot');row.mode='I2VA';
const take={id:'take',shot_id:'shot',state:'uncertain',error:'<script>bad</script>',created:'2026-09-09T00:00:00Z',source_hash:'a'.repeat(64),current:true};
p.video_renders.takes=[take];html=renderVideoProduction(p,row,drafts);
assert(/data-render-action="generate"[^>]+disabled/.test(html));
assert(html.includes('重新查詢原工作')&&!html.includes('<script>'));
assert(!html.includes('<video'));
take.state='queued';take.error='正在等候 GPU／影片服務；輪到會自動開始。';
html=renderVideoProduction(p,row,drafts);
assert(html.includes('排隊中 · 等候 GPU／影片服務'));
assert(/data-render-action="generate"[^>]+disabled/.test(html));
take.state='succeeded';take.video_url='/api/result';take.result={duration:10.125,width:864,height:480,audio_channels:2};
html=renderVideoProduction(p,row,drafts);assert(html.includes('<video controls preload="none"')&&html.includes('採用此成片'));
take.current=false;assert(!/data-render-action="adopt"/.test(renderVideoProduction(p,row,drafts)));
const handlers={},calls=[];let pending;
globalThis.document={addEventListener:(type,fn)=>handlers[type]=fn,querySelectorAll:()=>[]};
installVideoRenderUI({getProject:()=>p,drafts,api:async(path,body)=>{calls.push({path,body});return {id:'f'.repeat(16),state:'queued'};},modal:()=>{},refresh:async()=>{},guarded:fn=>pending=fn(),toast:()=>{}});
p.video_renders.takes=[];
const freeze={disabled:false,dataset:{renderAction:'freeze',id:'shot'}};
handlers.click({target:{closest:()=>freeze}});await pending;
assert(calls[0].path.endsWith('/freeze'));calls.length=0;
const b={disabled:false,dataset:{renderAction:'generate',id:'shot'}};
handlers.click({target:{closest:()=>b}});await pending;
assert.equal(calls.length,1);assert(calls[0].path.endsWith('/video-workflow/shot/generate'));
assert.equal(calls[0].body.frozen_id,'f'.repeat(16));assert.equal(calls[0].body.source_hash,'a'.repeat(64));assert(calls[0].body.request_key);
const recovery={disabled:false,dataset:{renderAction:'recover',id:'take'}};
handlers.click({target:{closest:()=>recovery}});await pending;
assert(calls[1].path.endsWith('/video-renders/take/recover'));
assert.equal(calls.filter(c=>c.path.endsWith('/generate')).length,1);
console.log('Video UI: draft guards, independent modes, unresolved deduplication, escaped states, playback/adoption and generate/recover endpoint separation passed.');

handlers.toggle({target:{matches:()=>true,isConnected:true,open:true,closest:()=>({dataset:{renderShot:'shot'}})}});
assert(renderVideoProduction(p,row,drafts).includes('data-render-settings open'));
handlers.toggle({target:{matches:()=>true,isConnected:true,open:false,closest:()=>({dataset:{renderShot:'shot'}})}});
assert(!renderVideoProduction(p,row,drafts).includes('data-render-settings open'));
p.video_renders.shots.shot.timing={duration:10,frame_rate:24,frame_count:243,aligned_duration:10.125};
html=renderVideoProduction(p,row,drafts);
assert(html.includes('value="10 秒" disabled')&&html.includes('value="24 fps" disabled'));
assert(html.includes('243 幀，預計 10.125 秒'));
assert(!html.includes('data-render-setting="duration"'));

// Steps must update synchronously even while the full project refresh never resolves.
let refreshes=0;
installVideoRenderUI({getProject:()=>p,drafts,api:async()=>({}),modal:()=>{},refresh:()=>{refreshes++;return new Promise(()=>{});},guarded:fn=>fn(),toast:()=>{}});
const stepField={value:20,disabled:false},stepSummary={textContent:'影片設定 · 864×480 · 20 步 · 不開二採'};
const section={dataset:{renderShot:'shot'},querySelector:selector=>selector==='[data-render-settings]'?null:selector.includes('summary')?stepSummary:stepField};
const selectTarget={tagName:'SELECT',dataset:{renderSetting:'acceleration_lora'},value:'minimax_h3_fl2v_turbo_4step_v1.1_768p_comfyui_bf16.safetensors',closest:()=>section};
handlers.change({target:selectTarget});
assert.equal(stepField.value,4);assert(stepField.disabled);assert(stepSummary.textContent.includes('· 4 步 ·'));
selectTarget.value='minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors';
handlers.input({target:selectTarget});handlers.change({target:selectTarget});
assert.equal(stepField.value,8);assert.equal(refreshes,2);
console.log('LoRA change-only and input/change events update locked steps immediately despite pending project refresh.');

// During an idle-gated deployment, new static code retains the old server's API.
p.video_renders.takes=[];delete p.workflow_contract_version;
html=renderVideoProduction(p,row,drafts);
assert(!html.includes('data-render-action="freeze"'));
assert(!/data-render-action="generate"[^>]*disabled/.test(html));
