import assert from 'node:assert/strict';
import {generationStatus,renderGenerationStatus} from '../static/generation-status.js';
import {jobDetailBody} from '../static/job-detail.js';
const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const job={id:'render',capability:'image',target_id:'frame',state:'succeeded',created:'2026-09-13T11:00:00Z',input:{},result:{image_path:'render.png'}};
const asset={id:'asset',target_id:'frame',job_id:job.id,status:'pending',created:'2026-09-13T11:01:00Z',image_output_quality:{valid:false,message:'全黑 <pixels>'}};
const project={jobs:[job],assets:[asset]};
const state=generationStatus(project,'frame');
assert.equal(state.phase,'failed');assert.equal(state.jobId,job.id);assert(!state.active);
const html=renderGenerationStatus(state,esc);
assert(html.includes('生成結果無有效畫面')&&!html.includes('圖片已生成'));
assert(html.includes('全黑 &lt;pixels&gt;')&&!html.includes('<pixels>'));
const details=jobDetailBody(job,project,{esc,providerName:()=>'',renderProductionMethod:()=>'',renderContextUsage:()=>'',imageLoraMarkup:()=>''});
assert(details.includes('輸出檔案無有效畫面'));
assert.equal(job.state,'succeeded');assert.equal(asset.status,'pending');
project.jobs.unshift({...job,id:'retry',state:'running',created:'2026-09-13T11:02:00Z'});
assert.equal(generationStatus(project,'frame').jobId,'retry');
assert.equal(generationStatus(project,'frame').active,true);
console.log('Invalid image output: failed presentation over historical success, escaped pixel diagnosis, unchanged records and active retry precedence passed.');
