import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=readFileSync('static/overview-status.js','utf8');
const {overviewState,renderOverviewStatus}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,attrs='',cls='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const empty={id:'p',source_kind:'outline',story_chapters:[],assets:[],jobs:[]};
assert.equal(overviewState(empty).next.action,'new-chapter');
assert.equal(overviewState({...empty,story_chapters:[{id:'c'}]}).next.section,'overview-chapters');
const p={...empty,production:{canon:[{id:'person',kind:'character'},{id:'voice',kind:'voice'}],shots:[{id:'s1',keyframes:[{id:'f1'}]},{id:'s2',keyframes:[{id:'f2'}]}]},assets:[{target_id:'old',status:'approved'},{target_id:'person',status:'stale'}]};
assert.equal(overviewState(p).references,0,'orphan and stale assets cannot count as approved references');
assert.equal(overviewState(p).referenceTotal,1,'voice identities are not image targets');
assert.equal(overviewState(p).next.page,'canon');
assert.equal(overviewState(p,3).next.page,'review','pending image decisions take precedence');
p.assets.push({target_id:'person',status:'approved'},{target_id:'person',status:'approved'},{target_id:'f1',status:'approved'});
assert.equal(overviewState(p).references,1,'multiple versions must not inflate progress');
assert.equal(overviewState(p).next.id,'s2','continue opens the first unfinished shot');
p.assets.push({target_id:'f2',status:'approved'});
assert.equal(overviewState(p).next.page,'video');
assert.match(overviewState(p).next.description,/檢查結果/,'image completion is not proof of render readiness');
p.video_renders={takes:[{id:'v1',shot_id:'s1',state:'succeeded',selected:true,current:true},{id:'v2',shot_id:'s1',state:'succeeded',selected:true,current:true},{shot_id:'s2',state:'succeeded',selected:true,current:false},{shot_id:'deleted',state:'succeeded',selected:true,current:true},{id:'uncertain',shot_id:'s2',state:'uncertain'}]};
p.jobs=[{id:'evil"',target_id:'<img>',capability:'<script>',state:'running'},{id:'old-failure',state:'failed'}];
p.postproduction={takes:[{id:'voice-active',state:'running'}]};
const s=overviewState(p);
assert.equal(s.adoptedVideos,1,'only current adopted videos of existing shots count once');
assert.equal(s.work.length,3,'include unresolved video and voice work, exclude historical failures');
const html=renderOverviewStatus(p,{esc,button,pendingImages:2});
assert(!html.includes('<script>')&&!html.includes('<img>'));
assert(html.includes('evil&quot;'));
assert(html.includes('data-page="review"'));
assert(!html.includes('data-action="generate"')&&!html.includes('data-action="retry"'),'dashboard navigation never submits production');
assert(html.includes('aria-label="製作流程"'));
console.log('Overview guidance: truthful counters, pending-review priority, exact next shot, empty states, active work, XSS and non-submitting navigation passed.');
