import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../static/provider-profile.js',import.meta.url),'utf8');
const {supportsProvider,profileLabel,renderProviderProfile}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const qwen={id:'local_qwen',name:'Qwen3.8',kind:'http',capabilities:['*']};
const providers=[qwen,{id:'manual',name:'Manual',kind:'manual',capabilities:['*']},{id:'comfy_local',name:'Comfy',kind:'comfy',capabilities:['image']}];
const profile={mode:'local_qwen',image_provider:'comfy_local',deepseek:{model:'deepseek-flash'}};
assert.equal(profileLabel({profile}),'Powered by Qwen3.8');
assert(supportsProvider(qwen,'future_skill'));
assert(!supportsProvider(qwen,'image'));
const html=renderProviderProfile({providers,profile},String);
assert.match(html,/value="local_qwen" selected/);
assert.match(html,/<div id="qwen-profile-options" >/);
assert.match(html,/<div id="deepseek-profile-options" hidden>/);
assert.match(html,/data-action="check-qwen"/);
const renderers=html.match(/<select name="image_provider">([\s\S]*?)<\/select>/)[1];
assert(!renderers.includes('local_qwen'));
assert.match(renderers,/value="comfy_local" selected/);
const app=await readFile(new URL('../static/app.js',import.meta.url),'utf8');
assert.match(app,/api\('\/settings\/qwen\/check',\{\}\)/);
assert.match(app,/\['astra','deepseek','local_qwen'\]\.includes\(values.mode\)/);
console.log('Qwen profile labels, image boundary, selected renderer and wiring passed.');
